version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
       - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  
  server:
    build:
      dockerfile : Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000" 